theme: jekyll-theme-leap-day
title: Comercial Simples Nordeste
subtitle: "Full Service Consultoria / Sangiovane Informática"
description: "Sistema Comercial"
keywords: Automação, Comercial, Sistema, CRM
show_downloads: true
google_analytics: UA-21710445-1
locale: pt_BR
charset: utf-8
encoding: utf-8
